export const PRODUCT_STATUS = {
  NOT_APPROVED: "NOT_APPROVED",
  WAITING_FOR_APPROVE: "WAITING_FOR_APPROVE",
  APPROVED: "APPROVED",
  DELETED: "DELETED",
} as const;

export type PRODUCT_STATUS =
  (typeof PRODUCT_STATUS)[keyof typeof PRODUCT_STATUS];
