export const EVENT_TYPE = {
  SHOW_TOAST: "SHOW_TOAST",

  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_APPROVED: "PRODUCT_APPROVED",
  PRODUCT_REJECTED: "PRODUCT_REJECTED",

  ORDER_CREATED: "ORDER_CREATED",
  ORDER_PAID: "ORDER_PAID",
  ORDER_CANCELED: "ORDER_CANCELED",

  BRAND_CREATED: "BRAND_CREATED",
  BRAND_UPDATED: "BRAND_UPDATED",
} as const;

export type EVENT_TYPE = (typeof EVENT_TYPE)[keyof typeof EVENT_TYPE];
